# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts

stages:
  - build
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -y lftp

cache:
  paths:
    - node_modules/

build:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - ./ci/build.sh

deploy:
  stage: deploy
  only:
    - master
  script:
    - ./ci/deploy.sh